//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LLMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class leas
    {
        public int id { get; set; }
        public int property_id { get; set; }
        public int tenant_id { get; set; }
        public System.DateTime start_date { get; set; }
        public System.DateTime end_date { get; set; }
        public decimal rent_amount { get; set; }
        public System.DateTime created_at { get; set; }
        public Nullable<System.DateTime> updated_at { get; set; }
        public string lease_clauses { get; set; }
        public int payment_due_day { get; set; }
        public string utility_by_owner { get; set; }
        public string utility_by_tenant { get; set; }
        public string renewal_term { get; set; }
        public string early_terminate_con { get; set; }
    
        public virtual property property { get; set; }
        public virtual tenant tenant { get; set; }
    }
}
