//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LLMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class property
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public property()
        {
            this.leases = new HashSet<leas>();
        }
    
        public int id { get; set; }
        public string address { get; set; }
        public int number_of_units { get; set; }
        public System.DateTime created_at { get; set; }
        public Nullable<System.DateTime> updated_at { get; set; }
        public string property_type { get; set; }
        public int size_in_sq_ft { get; set; }
        public System.DateTime year_built { get; set; }
        public decimal rental_price { get; set; }
        public string amenities { get; set; }
        public int status { get; set; }
        public string lease_terms { get; set; }
        public int image_id { get; set; }
        public string description { get; set; }
    
        public virtual image image { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<leas> leases { get; set; }
    }
}
