//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LLMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class tenant
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tenant()
        {
            this.leases = new HashSet<leas>();
        }
    
        public int id { get; set; }
        public string email { get; set; }
        public Nullable<System.DateTime> updated_at { get; set; }
        public string first_name { get; set; }
        public string last_name { get; set; }
        public string street_number { get; set; }
        public string street_name { get; set; }
        public string city_name { get; set; }
        public string postcode { get; set; }
        public string province { get; set; }
        public string phone_number { get; set; }
        public Nullable<int> profile_image_id { get; set; }
        public Nullable<System.DateTime> date_of_birth { get; set; }
        public string emergency_contact_name { get; set; }
        public string emergency_contact_number { get; set; }
        public string national_id { get; set; }
        public string employer_info { get; set; }
        public string bank_info { get; set; }
        public string reference_url { get; set; }
        public Nullable<bool> is_verified { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }

        public string ImageUrl { get; set; } // Add this property


        public virtual image image { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<leas> leases { get; set; }
    }
}
